MeterReadings.MvcApp/Controllers/AccountsController.cs
namespace MeterReadings.MvcApp.Controllers
{
	using System.Linq;
	using System.Threading.Tasks;
	using AutoMapper;
	using MeterReadings.Dto;
	using MeterReadings.Models;
	using MeterReadings.Service;
	using Microsoft.AspNetCore.Mvc;

	public class AccountsController : Controller
    {
		private readonly IMeterReadingsService _service;

		public AccountsController(IMeterReadingsService service)
		{
			_service = service;
		}

        // GET: Accounts
        public async Task<IActionResult> Index()
        {
			return View(await _service.Account.ReadAsync<AccountViewModel>(ViewModelMapperConfig.Config));
        }

		// GET: Accounts/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			AccountDto account = (await _service.Account.ReadAsync(x => x.Id == id.Value)).FirstOrDefault();
			if (account == null)
			{
				return NotFound();
			}

			return View(new Mapper(ViewModelMapperConfig.Config).Map<AccountViewModel>(account));
		}

		// GET: Accounts/Create
		public IActionResult Create()
        {
            return View();
        }

		// POST: Accounts/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,FirstName,LastName")] AccountDto account)
		{
			if (ModelState.IsValid)
			{
				await _service.Account.CreateAsync(account);
				return RedirectToAction(nameof(Index));
			}
			return View(new Mapper(ViewModelMapperConfig.Config).Map<AccountViewModel>(account));
		}

		// GET: Accounts/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			AccountDto account = (await _service.Account.ReadAsync(x => x.Id == id.Value)).FirstOrDefault();
			if (account == null)
			{
				return NotFound();
			}
			return View(new Mapper(ViewModelMapperConfig.Config).Map<AccountViewModel>(account));
		}

		// POST: Accounts/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName")] AccountDto account)
		{
			if (id != account.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				await _service.Account.UpdateAsync(account);
				return RedirectToAction(nameof(Index));
			}
			return View(new Mapper(ViewModelMapperConfig.Config).Map<AccountViewModel>(account));
		}

		// GET: Accounts/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			AccountDto account = (await _service.Account.ReadAsync(x => x.Id == id.Value)).FirstOrDefault();
			if (account == null)
			{
				return NotFound();
			}

			return View(new Mapper(ViewModelMapperConfig.Config).Map<AccountViewModel>(account));
		}

		// POST: Accounts/Delete/5
		[HttpPost]
		[ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			await _service.Account.DeleteAsync((await _service.Account.ReadAsync(x => x.Id == id)).FirstOrDefault());
			return RedirectToAction(nameof(Index));
		}
	}
}

MeterReadings.MvcApp/Controllers/HomeController.cs
namespace MeterReadings.MvcApp.Controllers
{
	using System.Diagnostics;
	using MeterReadings.Models;
	using Microsoft.AspNetCore.Mvc;

	public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MeterReadings.MvcApp/Controllers/MeterReadingsController.cs
namespace MeterReadings.MvcApp.Controllers
{
	using System.Linq;
	using System.Threading.Tasks;
	using AutoMapper;
	using MeterReadings.Dto;
	using MeterReadings.Models;
	using MeterReadings.Service;
	using Microsoft.AspNetCore.Mvc;
	using Microsoft.AspNetCore.Mvc.Rendering;

	public class MeterReadingsController : Controller
    {
		private readonly IMeterReadingsService _service;

		public MeterReadingsController(IMeterReadingsService service)
        {
			_service = service;
        }

        // GET: MeterReadings
        public async Task<IActionResult> Index()
        {
			return View(await _service.MeterReading.ReadAsync<MeterReadingViewModel>(ViewModelMapperConfig.Config));
        }

		// GET: MeterReadings/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			MeterReadingDto meterReading = (await _service.MeterReading.ReadAsync(x => x.Id == id.Value)).FirstOrDefault();
			if (meterReading == null)
			{
				return NotFound();
			}

			return View(new Mapper(ViewModelMapperConfig.Config).Map<MeterReadingViewModel>(meterReading));
		}

		// GET: MeterReadings/Create
		public async Task<IActionResult> Create()
        {
            ViewData["AccountId"] = new SelectList(await _service.Account.ReadAsync(), "Id", "Id");
            return View();
        }

		// POST: MeterReadings/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,AccountId,MeterReadingDateTime,MeterReadingValue")] MeterReadingDto meterReading)
		{
			if (ModelState.IsValid)
			{
				await _service.MeterReading.CreateAsync(meterReading);
				return RedirectToAction(nameof(Index));
			}
			ViewData["AccountId"] = new SelectList(await _service.Account.ReadAsync(), "Id", "Id", meterReading.AccountId);
			return View(new Mapper(ViewModelMapperConfig.Config).Map<MeterReadingViewModel>(meterReading));
		}

		// GET: MeterReadings/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			MeterReadingDto meterReading = (await _service.MeterReading.ReadAsync(x => x.Id == id.Value)).FirstOrDefault();
			if (meterReading == null)
			{
				return NotFound();
			}
			ViewData["AccountId"] = new SelectList(await _service.Account.ReadAsync(), "Id", "Id", meterReading.AccountId);
			return View(new Mapper(ViewModelMapperConfig.Config).Map<MeterReadingViewModel>(meterReading));
		}

		// POST: MeterReadings/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,AccountId,MeterReadingDateTime,MeterReadingValue")] MeterReadingDto meterReading)
		{
			if (id != meterReading.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				await _service.MeterReading.UpdateAsync(meterReading);
				return RedirectToAction(nameof(Index));
			}
			ViewData["AccountId"] = new SelectList(await _service.Account.ReadAsync(), "Id", "Id", meterReading.AccountId);
			return View(new Mapper(ViewModelMapperConfig.Config).Map<MeterReadingViewModel>(meterReading));
		}

		// GET: MeterReadings/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			MeterReadingDto meterReading = (await _service.MeterReading.ReadAsync(x => x.Id == id.Value)).FirstOrDefault();
			if (meterReading == null)
			{
				return NotFound();
			}

			return View(new Mapper(ViewModelMapperConfig.Config).Map<MeterReadingViewModel>(meterReading));
		}

		// POST: MeterReadings/Delete/5
		[HttpPost]
		[ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			await _service.MeterReading.DeleteAsync((await _service.MeterReading.ReadAsync(x => x.Id == id)).FirstOrDefault());
			return RedirectToAction(nameof(Index));
		}
	}
}

MeterReadings.MvcApp/Views/Accounts/Create.cshtml
@model MeterReadings.Models.AccountViewModel

@{
    ViewData["Title"] = "Create Account";
}

<h1>@ViewData["Title"]</h1>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MeterReadings.MvcApp/Views/Accounts/Delete.cshtml
@model MeterReadings.Models.AccountViewModel

@{
    ViewData["Title"] = "Delete Account";
}

<h1>@ViewData["Title"]</h1>
<h3>Are you sure you want to delete this?</h3>
<hr />

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MeterReadings.MvcApp/Views/Accounts/Details.cshtml
@model MeterReadings.Models.AccountViewModel

@{
    ViewData["Title"] = "Account Details";
}

<h1>@ViewData["Title"]</h1>
<hr />

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MeterReadings.MvcApp/Views/Accounts/Edit.cshtml
@model MeterReadings.Models.AccountViewModel

@{
    ViewData["Title"] = "Edit Account";
}

<h1>@ViewData["Title"]</h1>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MeterReadings.MvcApp/Views/Accounts/Index.cshtml
@model IEnumerable<MeterReadings.Models.AccountViewModel>

@{
    ViewData["Title"] = "Accounts";
}

<h1>@ViewData["Title"]</h1>
<hr />

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

MeterReadings.MvcApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MeterReadings.MvcApp/Views/MeterReadings/Create.cshtml
@model MeterReadings.Models.MeterReadingViewModel

@{
    ViewData["Title"] = "Create Meter Reading";
}

<h1>@ViewData["Title"]</h1>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AccountId" class="control-label"></label>
                <select asp-for="AccountId" class ="form-control" asp-items="ViewBag.AccountId"></select>
            </div>
            <div class="form-group">
                <label asp-for="MeterReadingDateTime" class="control-label"></label>
                <input asp-for="MeterReadingDateTime" class="form-control" />
                <span asp-validation-for="MeterReadingDateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MeterReadingValue" class="control-label"></label>
                <input asp-for="MeterReadingValue" class="form-control" />
                <span asp-validation-for="MeterReadingValue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MeterReadings.MvcApp/Views/MeterReadings/Delete.cshtml
@model MeterReadings.Models.MeterReadingViewModel

@{
    ViewData["Title"] = "Delete Meter Reading";
}

<h1>@ViewData["Title"]</h1>
<h3>Are you sure you want to delete this?</h3>
<hr />

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AccountId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AccountId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MeterReadingDateTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MeterReadingDateTime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MeterReadingValue)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MeterReadingValue)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MeterReadings.MvcApp/Views/MeterReadings/Details.cshtml
@model MeterReadings.Models.MeterReadingViewModel

@{
    ViewData["Title"] = "Meter Reading Details";
}

<h1>@ViewData["Title"]</h1>
<hr />

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AccountId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AccountId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MeterReadingDateTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MeterReadingDateTime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MeterReadingValue)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MeterReadingValue)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MeterReadings.MvcApp/Views/MeterReadings/Edit.cshtml
@model MeterReadings.Models.MeterReadingViewModel

@{
    ViewData["Title"] = "Edit Meter Reading";
}

<h1>@ViewData["Title"]</h1>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="AccountId" class="control-label"></label>
                <select asp-for="AccountId" class="form-control" asp-items="ViewBag.AccountId"></select>
                <span asp-validation-for="AccountId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" disabled="disabled" />
            </div>
            <div class="form-group">
                <label asp-for="MeterReadingDateTime" class="control-label"></label>
                <input asp-for="MeterReadingDateTime" class="form-control" />
                <span asp-validation-for="MeterReadingDateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MeterReadingValue" class="control-label"></label>
                <input asp-for="MeterReadingValue" class="form-control" />
                <span asp-validation-for="MeterReadingValue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MeterReadings.MvcApp/Views/MeterReadings/Index.cshtml
@model IEnumerable<MeterReadings.Models.MeterReadingViewModel>

@{
    ViewData["Title"] = "Meter Readings";
}

<h1>@ViewData["Title"]</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AccountId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MeterReadingDateTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MeterReadingValue)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AccountId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MeterReadingDateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MeterReadingValue)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

MeterReadings.MvcApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Meter Readings MVC App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Meter Readings MVC App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Accounts" asp-action="Index">Accounts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MeterReadings" asp-action="Index">Meter Readings</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Andy Hawkins
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>